#!/bin/bash
# gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

include ~/.config/sway/themes/catppuccin-mocha

client.focused           $lavender $base $text  $rosewater $lavender
client.focused_inactive  $overlay0 $base $text  $rosewater $overlay0
client.unfocused         $overlay0 $base $text  $rosewater $overlay0
client.urgent            $peach    $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base

# bar
# bar {
#   colors {
#     background         $base
#     statusline         $text
#     focused_statusline $text
#     focused_separator  $base

#     # target           border bg        text
#     focused_workspace  $base  $mauve    $crust
#     active_workspace   $base  $surface2 $text
#     inactive_workspace $base  $base     $text
#     urgent_workspace   $base  $red      $crust
#   }
# }
