
# There should also be a ~/.local/share/simple_package_manager/packages.toml
# That has the current system's install state for them & version & such

[a]
name = "AA" # A nice display name for me
description = "" # Super brief about this guy
category = "" # "game" | "utility"
packageType = "cargo" # "executable" | "cargo" | "source" | "flatpak"
ref = "starship" # The package itself
args = "--locked" # Any fancyness when downloading the package


#org.inkscape.Inkscape
#org.mozilla.Thunderbird
#org.libreoffice.LibreOffice
#org.kde.kdenlive
#org.gimp.GIMP
#org.darktable.Darktable
#im.riot.Riot
#org.kde.krita
#io.podman_desktop.PodmanDesktop
#org.kde.kate
#org.kde.kpat

# Cargo
# cargo install starship --locked # starship makes our bash prompt prettier
# cargo install bottom --locked # Top replacement
# cargo install tuifeed --locked # TUI Rss feeds (probs going to replace)
# cargo install cargo-expand --locked # More cargo bits
# cargo install eza # An ls replacer (that also replaces exa)
# cargo install bat --locked # A cat replacer
# # The Yazi TUI file manager & fd/ripgrep for file searching
# cargo install --locked yazi-fm yazi-cli
# cargo install fd-find
# cargo install ripgrep
