# yazi.toml
[manager]
show_hidden = false
linemode = "size_and_mtime"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 5
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]


# https://yazi-rs.github.io/docs/configuration/keymap/

[mgr]
keymap = [
	{ on = "<C-_>", run = "hardlink", desc = "Hardlink the given folder" },
]

# [opener]
# edit = [
# 	{ run = "vlc %s", blick = true, for = "unix" }
# ]
